services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '5000:5000'
      - '9229:9229'
    command: npm run start:dev
    depends_on:
      - mysql
    restart: always
  mysql:
    container_name: mysql
    image: mysql:8.0.30
    environment:
      MYSQL_DATABASE: 'shop'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'my_password'
      MYSQL_ROOT_PASSWORD: 'my_password'
    ports:
      - '3310:3310'
    volumes:
      - my-db:/var/lib/mysql
    restart: always

volumes:
  my-db: