services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .production.env
    volumes:
      - /app
      - /app/node_modules
    ports:
      - '5000:5000'
    command: npm run start:prod
    depends_on:
      - mysql
    restart: always
  mysql:
    container_name: database
    image: mysql:8.0.30
    environment:
      MYSQL_DATABASE: 'shop'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3310:3310'
    volumes:
      - my-db:/var/lib/mysql
    restart: always

volumes:
  my-db: