services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .production.env
    volumes:
      - .:/app
    ports:
      - '5000:5000'
    command: node dist/main.js
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
  mysql:
    container_name: database
    image: mysql:8.0.30
    environment:
      MYSQL_DATABASE: 'shop'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3310:3306'
    volumes:
      - db:/var/lib/mysql
      - ./dump_sql:/docker-entrypoint-initdb.d/
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 20s
      timeout: 5s
      retries: 5

volumes:
  db: